# run_state is used to control the execution and shutdown of yesican
RUN_STATE_RUNNING = 20
RUN_STATE_STARTING = 6
RUN_STATE_PENDING_CAN_OPEN = 5
RUN_STATE_CAN_INTERFACE_FAILURE = 4
RUN_STATE_PENDING_SHUTDOWN = 3
RUN_STATE_AWAITING_BACKEND = 2
RUN_STATE_BACKEND_STOPPED = 1
RUN_STATE_EXITING = 0

DM_GEAR_SHIFT_INDICATOR = 0
DM_PIT_SPEED_INDICATOR = 1
DM_BRAKE_TRACE_PLOT = 2
DM_FUEL_BURN = 3
DM_CONFIGURATION = 4
